Repository nodak-v2/Nodak-FE, pull requests merged in 2024-06, with the labels that each got.

#87 [#86] Feat: 메인페이지 채널 이동과 검색 api 연결
  next.config.js
  src/apis/post.ts
  src/app/(main)/_component/ChipContainer.tsx
  src/app/(main)/constants.ts
  src/app/(main)/utils.ts
  src/app/page.tsx
Labels: ✨Feature

#84 [#81] Feat: 메인페이지의 postList api 와 연결
  .gitignore
  public/placeHolder_130.png
  public/placeHolder_20.png
  src/apis/post.ts
  src/app/(main)/constants.ts
  src/app/(main)/utils.ts
  src/app/_components/ChipContainer.tsx
  src/app/_components/PostItem.tsx
  src/app/page.tsx
  src/mocks/handlers/post-list.ts
Labels: ✨Feature

#100 [#99] Chore: tailwind 설정 추가
  src/app/globals.css
  src/app/layout.tsx
  src/components/Button/Button.tsx
  src/components/Drawer/index.tsx
  src/components/TextInput/index.tsx
  src/components/Textarea/index.tsx
  src/components/Tooltip/Tooltip.tsx
  src/stories/tailwind-configure/colors.stories.tsx
  src/stories/tailwind-configure/fonts.stories.tsx
  tailwind.config.js
Labels: ⚙️ Chore

#105 [#101] Refactor: 이미지 업로드 컴포넌트 api 연결
  next.config.js
  src/apis/image.ts
  src/app/(post)/createPost/_component/ImageUploader.tsx
  src/components/ImageUploadButton/hooks/useImageUpload.ts
  src/components/ImageUploadButton/index.tsx
Labels: ✨Feature, 🔨 Refactor

#98 [#97] Style: 메인페이지 ui 수정
  public/icon-sprite.svg
  src/apis/myInfo.ts
  src/apis/postList.ts
  src/app/(main)/utils.ts
  src/app/(post)/comment/[postId]/layout.tsx
  src/app/(post)/comment/[postId]/page.tsx
  src/app/(post)/comment/_components/CommentInfo.tsx
  src/app/(post)/comment/_components/PostComment.tsx
  src/app/(post)/comment/hooks/useCreateComment.ts
  src/app/_components/Chip.tsx
  src/app/_components/ChipContainer.tsx
  src/app/_components/PostItem.tsx
  src/app/page.tsx
  src/components/GNB/index.tsx
  src/components/Icon/index.tsx
  src/components/Icon/type.ts
  src/components/POPup/index.tsx
  src/components/Topbar/index.tsx
  src/stories/components/CommentInfo.stories.tsx
  src/stories/components/PostComment.stories.tsx
  src/stories/components/PostItem.stories.tsx
Labels: 🎨 Style

#92 [#90] Feat: mainpage 의 요청 api를 fetch 에서 tanstack 쿼리로 변경합니다.
  public/icon-sprite.svg
  src/apis/myInfo.ts
  src/apis/post.ts
  src/apis/postDetail.ts
  src/apis/postList.ts
  src/app/(main)/utils.ts
  src/app/(post)/comment/[postId]/layout.tsx
  src/app/(post)/comment/[postId]/page.tsx
  src/app/(post)/comment/_components/CommentInfo.tsx
  src/app/(post)/comment/_components/PostComment.tsx
  src/app/(post)/comment/hooks/useCreateComment.ts
  src/app/(post)/createPost/_component/PostForm/index.tsx
  src/app/(post)/result/[postId]/_components/CommentLink.tsx
  src/app/(post)/result/[postId]/actions.ts
  src/app/(post)/result/[postId]/page.tsx
  src/app/_components/Chip.tsx
  src/app/_components/ChipContainer.tsx
  src/app/_components/PostItem.tsx
  src/app/page.tsx
  src/components/GNB/index.tsx
  src/components/Icon/index.tsx
  src/components/Icon/type.ts
  src/components/POPup/index.tsx
  src/components/Topbar/index.tsx
  src/mocks/handlers/post-detail.ts
  src/mocks/handlers/post-list.ts
  src/stories/components/CommentInfo.stories.tsx
  src/stories/components/PostComment.stories.tsx
  src/stories/components/PostItem.stories.tsx
  src/stories/pages/users.stories.tsx
Labels: ✨Feature, 🔨 Refactor

#102 [#94] Feat: 게시글 상세페이지 구현
  public/icon-sprite.svg
  public/picky-logo.png
  public/user-square.png
  src/apis/comments.ts
  src/apis/like.ts
  src/apis/myInfo.ts
  src/apis/post.ts
  src/apis/vote.ts
  src/app/(post)/comment/_components/PostComment.tsx
  src/app/(post)/createPost/page.tsx
  src/app/(post)/result/[postId]/_components/CommentInput/index.tsx
  src/app/(post)/result/[postId]/_components/Comments/CommentItem.tsx
  src/app/(post)/result/[postId]/_components/Comments/CommentList.tsx
  src/app/(post)/result/[postId]/_components/Comments/OwnCommentChip.tsx
  src/app/(post)/result/[postId]/_components/LikeButton.tsx
  src/app/(post)/result/[postId]/_components/Posting/PostingButton.tsx
  src/app/(post)/result/[postId]/_components/Posting/VoteForm.tsx
  src/app/(post)/result/[postId]/_components/Posting/VoteResult.tsx
  src/app/(post)/result/[postId]/_components/Posting/index.tsx
  src/app/(post)/result/[postId]/_components/VoteBlock/VoteBlockForm.tsx
  src/app/(post)/result/[postId]/_components/VoteBlock/index.tsx
  src/app/(post)/result/[postId]/actions.ts
  src/app/(post)/result/[postId]/hooks/useCreateComment.ts
  src/app/(post)/result/[postId]/hooks/useCreateVote.ts
  src/app/(post)/result/[postId]/hooks/usePostingLike.ts
  src/app/(post)/result/[postId]/layout.tsx
  src/app/(post)/result/[postId]/page.tsx
  src/app/globals.css
  src/app/layout.tsx
  src/app/page.tsx
  src/components/Icon/index.tsx
  src/components/Icon/type.ts
  src/components/Topbar/index.tsx
  src/stories/components/Topbar.stories.tsx
  src/stories/components/VoteResult.stories.tsx
  src/stories/pages/result.stories.tsx
  tailwind.config.js
Labels: ✨Feature

#117 [#114] Style: 로그인페이지 스타일링
  public/Logo.png
  src/app/(auth)/signin/page.tsx
  src/components/Icon/type.ts
Labels: 🎨 Style

#120 [#118] Style: 메인화면 게시물 없을 때 스타일링 추가
  public/icon-sprite.svg
  src/app/page.tsx
  src/components/EmptyPage/index.tsx
  src/components/Icon/type.ts
Labels: 🎨 Style

#111 [#110] Feat: 모달 컴포넌트 구현 및 적용
  src/app/(post)/createPost/_component/ImageUploader.tsx
  src/components/Button/Button.tsx
  src/components/Modal/ConfirmationModal.tsx
  src/components/Modal/index.tsx
Labels: ✨Feature, 🎨 Style

#128 [#116] Style: 알림페이지 UI제작
  src/app/notification/_components/NotificationItem.tsx
  src/app/notification/page.tsx
  src/components/GNB/index.tsx
Labels: 🎨 Style

#119 [#115] Refactor: 메인페이지 관련 리팩토링
  src/apis/postList.ts
  src/app/(main)/constants.ts
  src/app/(main)/utils.ts
  src/app/_components/Chip.tsx
  src/app/_components/ChipContainer.tsx
  src/app/_components/PostItem.tsx
  src/app/page.tsx
  src/utils/isValidImageUrl.ts
Labels: 🔨 Refactor

#126 [#121] Feat: toast 컴포넌트 구현
  package.json
  pnpm-lock.yaml
  src/app/(post)/createPost/_component/ImageUploader.tsx
  src/app/(post)/createPost/_component/PostForm/index.tsx
  src/app/(post)/createPost/page.tsx
  src/app/_components/Toast.tsx
  src/app/layout.tsx
Labels: ✨Feature

#131 [#129] Feat: PostForm 내부 컴포넌트 수정
  public/icon-sprite.svg
  src/apis/createPost.ts
  src/apis/post.ts
  src/apis/postDetail.ts
  src/app/(post)/createPost/_component/ImageUploader.tsx
  src/app/(post)/createPost/_component/PostForm/formSchema.ts
  src/app/(post)/createPost/_component/PostForm/index.tsx
  src/app/(post)/createPost/_component/PostForm/useCreatePost.ts
  src/app/(post)/createPost/page.tsx
  src/app/(post)/result/[postId]/_components/CommentLink.tsx
  src/app/(post)/result/[postId]/_components/EditLinks.tsx
  src/app/(post)/result/[postId]/_components/LikeButton.tsx
  src/app/(post)/result/[postId]/_components/Posting/PostingButton.tsx
  src/app/(post)/result/[postId]/_components/Posting/index.tsx
  src/app/(post)/result/[postId]/_components/ProfileBlock.tsx
  src/app/(post)/result/[postId]/_components/VoteBlock/VoteBlockForm.tsx
  src/app/(post)/result/[postId]/_components/VoteBlock/VoteProgress.tsx
  src/app/(post)/result/[postId]/_components/VoteBlock/index.tsx
  src/app/(post)/result/[postId]/actions.ts
  src/app/(post)/result/[postId]/page.tsx
  src/app/globals.css
  src/app/profile/[userId]/_components/ActiveGrass.tsx
  src/components/FormField/index.tsx
  src/components/Icon/type.ts
  src/components/ImageUploadButton/hooks/useImageUpload.ts
  src/components/ImageUploadButton/index.tsx
  src/components/Selector/index.tsx
  src/components/TextInput/index.tsx
  src/components/Textarea/index.tsx
  src/components/TimeInput/index.tsx
  src/components/Tooltip/Tooltip.tsx
  src/components/Topbar/index.tsx
  src/components/VoteForm/index.tsx
  src/mocks/handlers/post-detail.ts
  src/stories/components/ProfileBlock.stories.tsx
  src/stories/components/VoteProgress.stories.tsx
Labels: ✨Feature, 🎨 Style

#134 [#133] Fix: 기존의 쓸모없는 코드 제거
  public/SlideD0.webp
  public/SlideD1.webp
  public/SlideD2.webp
  public/SlideD3.webp
  public/SlideD4.webp
  public/app-Icon/icon-128x128.png
  public/app-Icon/icon-152x152.png
  public/app-Icon/icon-180x180.png
  public/app-Icon/icon-192x192.png
  public/app-Icon/icon-512x512.png
  public/app-Icon/icon.ico
  public/manifest.json
  public/picky/Logo.png
  public/picky/kakao.png
  public/picky/picky-logo.png
  public/picky/user-square.png
  public/placeHolder_130.png
  public/placeHolder_20.png
  public/노닥노닥.png
  src/apis/api.ts
  src/apis/comments.ts
  src/apis/like.ts
  src/apis/myInfo.ts
  src/apis/post.ts
  src/apis/profile.ts
  src/apis/vote.ts
  src/app/(auth)/signin/page.tsx
  src/app/(post)/createPost/_component/PostForm/index.tsx
  src/app/layout.tsx
  src/components/Toast/index.tsx
  src/mocks/handlers/vote.ts
Labels: 🛠️ Fix, 🔨 Refactor

#137 [#136] Style: 토스트 컴포넌트 위치 수정
  src/app/layout.tsx
Labels: 🎨 Style
