Repository nodak-v2/Nodak-FE, pull requests merged in 2024-05, with the labels that each got.

#27 [#26] Chore: storybook deploy comment 기능 추가
  .github/workflows/storybook.yaml
Labels: ⚙️ Chore

#32 [#31] Fix: 빌드오류 해결
  src/app/_components/TextInput/index.tsx
Labels: 🛠️ Fix

#16 [#7] Feat: Chip, ChipContainer컴포넌트 구현
  src/app/_components/Chip/index.tsx
  src/app/_components/ChipContainer/index.tsx
  src/stories/components/Chip.stories.tsx
  src/stories/components/ChipContainer.stories.tsx
Labels: ✨Feature

#35 [#34] Feat: button컴포넌트 구현
  .storybook/preview.tsx
  src/app/_components/Button/Button.tsx
  src/stories/components/Button.stories.tsx
Labels: ✨Feature

#39 [#37] Feat: PostResult 페이지에 대한 storybook + msw 구성
  .storybook/preview.tsx
  src/apis/post.ts
  src/apis/types.ts
  src/app/result/[postId]/page.tsx
  src/mocks/handlers/index.ts
  src/mocks/handlers/post-detail.ts
  src/mocks/handlers/post-list.ts
  src/mocks/handlers/post.ts
  src/stories/decorator.tsx
  src/stories/msw-exmple/msw.mdx
  src/stories/msw-exmple/msw.stories.tsx
  src/stories/pages/result.stories.tsx
Labels: ✨Feature

#30 [#9] Feat: 소개창 팝업으로 구현
  package.json
  pnpm-lock.yaml
  public/SlideD0.webp
  public/SlideD1.webp
  public/SlideD2.webp
  public/SlideD3.webp
  public/SlideD4.webp
  src/app/_components/Popup.tsx
  src/app/globals.css
  src/app/page.tsx
  src/stories/components/Popup.stories.tsx
Labels: ✨Feature

#45 [#44] Feat: ProfileBlock 컴포넌트 구현
  src/app/result/[postId]/_components/ProfileBlock.tsx
  src/stories/components/ProfileBlock.stories.tsx
Labels: ✨Feature

#40 [#33] Feat: 유저 목록 페이지 구현
  package.json
  pnpm-lock.yaml
  src/app/globals.css
  src/app/layout.tsx
  src/app/users/_components/DrawerButton.tsx
  src/app/users/_components/DrawerContent.tsx
  src/app/users/_components/UserList.tsx
  src/app/users/page.tsx
  src/components/ui/Drawer.tsx
  src/stories/decorator.tsx
  src/stories/pages/users.stories.tsx
Labels: ✨Feature

#57 [#56] Feat: TopBar 공통컴포넌트 구현
  public/icon-sprite.svg
  src/app/_components/Topbar/index.tsx
  src/components/Icon/type.ts
  src/stories/components/Topbar.stories.tsx
Labels: ✨Feature

#46 [#36] 카카오 로그인 UI
  public/kakao.svg
  src/app/signin/page.tsx
Labels: ✨Feature

#41 [#38] Feat: 공통컴포넌트구현 - ImageUploader
  public/icon-sprite.svg
  src/app/_components/ImageUploadButton/index.tsx
  src/app/createPost/_component/ImageUploader.tsx
  src/app/createPost/page.tsx
  src/components/Icon/type.ts
  src/stories/components/ImageUploader.stories.tsx
Labels: ✨Feature

#54 [#51] Feat: 투표폼 컴포넌트 구현
  public/icon-sprite.svg
  src/app/_components/VoteForm/index.tsx
  src/app/result/[postId]/_components/VoteResult.tsx
  src/components/Icon/type.ts
  src/stories/components/VoteForm.stories.tsx
  src/stories/components/VoteResult.stories.tsx
Labels: ✨Feature

#53 [#52] Feat: 메인페이지 구현
  public/icon-sprite.svg
  src/app/_components/ChipContainer/index.tsx
  src/app/_components/GNB.tsx
  src/app/main/_component/Chip.tsx
  src/app/main/_component/ChipContainer.tsx
  src/app/main/_component/PostItem.tsx
  src/app/main/page.tsx
  src/components/Icon/type.ts
  src/stories/components/Chip.stories.tsx
  src/stories/components/ChipContainer.stories.tsx
  src/stories/components/PostItem.stories.tsx
Labels: ✨Feature

#55 [#50] Feat : post 결과 페이지 구현
  public/icon-sprite.svg
  src/apis/post.ts
  src/apis/types.ts
  src/apis/vote.ts
  src/app/layout.tsx
  src/app/result/[postId]/_components/CommentLink.tsx
  src/app/result/[postId]/_components/EditLinks.tsx
  src/app/result/[postId]/_components/LikeIcon.tsx
  src/app/result/[postId]/_components/ProfileBlock.tsx
  src/app/result/[postId]/_components/VoteResult.tsx
  src/app/result/[postId]/page.tsx
  src/components/Icon/type.ts
  src/mocks/handlers/index.ts
  src/mocks/handlers/post-detail.ts
  src/mocks/handlers/post-list.ts
  src/mocks/handlers/vote.ts
  src/stories/pages/result.stories.tsx
Labels: ✨Feature

#49 [#47] 댓글페이지 UI 구현
  src/app/comment/_components/CommentInfo.tsx
  src/app/comment/_components/PostComment.tsx
  src/app/comment/page.tsx
  src/stories/components/CommentInfo.stories.tsx
  src/stories/components/PostComment.stories.tsx
Labels: ✨Feature

#58 [#48] Selector 구현
  public/icon-sprite.svg
  src/app/_components/Selector/index.tsx
  src/app/_components/Selector/useDropdown.tsx
  src/components/Icon/type.ts
  src/stories/components/Selector.stories.tsx
Labels: ✨Feature

#61 [#60] Feat: 좋아요 버튼 fetch 구현
  src/apis/constants.ts
  src/apis/post.ts
  src/apis/vote.ts
  src/app/layout.tsx
  src/app/result/[postId]/_components/LikeButton.tsx
  src/app/result/[postId]/_components/LikeIcon.tsx
  src/app/result/[postId]/actions.ts
  src/app/result/[postId]/page.tsx
  src/mocks/handlers/post-detail.ts
  src/mocks/handlers/post-list.ts
  src/mocks/handlers/vote.ts
Labels: ✨Feature

#69 [#67] 시간 계산 함수 제작
  src/utils/timeOffset.ts
Labels: ✨Feature

#82 [#77] Feat: OAuth2
  src/app/redirect/page.tsx
  src/app/signin/page.tsx
Labels: ✨Feature

#85 [#83] Feat: 댓글페이지 UI수정 및 API 연결
  src/apis/comments.ts
  src/apis/constants.ts
  src/app/_components/Topbar/index.tsx
  src/app/comment/[postId]/layout.tsx
  src/app/comment/[postId]/page.tsx
  src/app/comment/_components/CommentInfo.tsx
  src/app/comment/_components/PostComment.tsx
  src/app/comment/page.tsx
  src/app/layout.tsx
  src/instrumentation.ts
  src/mocks/MSWComponent.tsx
  src/stories/components/CommentInfo.stories.tsx
  src/stories/components/Topbar.stories.tsx
Labels: ✨Feature

#68 [#65]프로필 페이지
  public/camera.svg
  public/close.svg
  src/app/_components/Tooltip/Tooltip.tsx
  src/app/_components/Tooltip/TooltipArrow.tsx
  src/app/profile/[userId]/_components/ActiveGrass.tsx
  src/app/profile/[userId]/_components/UserInfo.tsx
  src/hooks/useHover.ts
  tailwind.config.js
Labels: ✨Feature

#76 [#75] Feat: 결과 페이지 api 연결
  src/apis/post.ts
  src/apis/vote.ts
Labels: ✨Feature

#74 [#70] Refactor: result 페이지 api response 타입 수정
  src/apis/constants.ts
  src/apis/post.ts
  src/apis/vote.ts
  src/app/result/[postId]/_components/ProfileBlock.tsx
  src/app/result/[postId]/_components/VoteBlock/VoteBlockForm.tsx
  src/app/result/[postId]/_components/VoteBlock/VoteProgress.tsx
  src/app/result/[postId]/_components/VoteBlock/index.tsx
  src/app/result/[postId]/page.tsx
  src/instrumentation.ts
  src/mocks/MSWComponent.tsx
  src/mocks/handlers/post-detail.ts
  src/mocks/handlers/vote.ts
  src/stories/components/ProfileBlock.stories.tsx
  src/stories/components/VoteProgress.stories.tsx
  src/stories/components/VoteResult.stories.tsx
  src/stories/pages/result.stories.tsx
Labels: 🔨 Refactor
