Repository nodak-v2/Nodak-FE, pull requests merged in 2024-04, with the labels that each got.

#3 [#1] Init: 프로젝트 초기 세팅
  .eslintrc.json
  .github/ISSUE_TEMPLATE/이슈템플릿.md
  .github/pull_request_template.md
  .github/workflows/next-build.yaml
  .github/workflows/storybook.yaml
  .gitignore
  .husky/commit-msg
  .husky/pre-commit
  .lintstagedrc.js
  .prettierrc
  .storybook/main.ts
  .storybook/preview.ts
  .vscode/setting.json
  README.md
  commitlint.config.cjs
  next.config.mjs
  package-lock.json
  package.json
  pnpm-lock.yaml
  postcss.config.mjs
  public/next.svg
  public/vercel.svg
  src/app/favicon.ico
  src/app/layout.tsx
  src/app/page.tsx
  src/stories/Button.stories.ts
  src/stories/Button.tsx
  src/stories/Configure.mdx
  src/stories/Header.stories.ts
  src/stories/Header.tsx
  src/stories/Page.stories.ts
  src/stories/Page.tsx
  src/stories/assets/accessibility.png
  src/stories/assets/accessibility.svg
  src/stories/assets/addon-library.png
  src/stories/assets/assets.png
  src/stories/assets/avif-test-image.avif
  src/stories/assets/context.png
  src/stories/assets/discord.svg
  src/stories/assets/docs.png
  src/stories/assets/figma-plugin.png
  src/stories/assets/github.svg
  src/stories/assets/share.png
  src/stories/assets/styling.png
  src/stories/assets/testing.png
  src/stories/assets/theming.png
  src/stories/assets/tutorials.svg
  src/stories/assets/youtube.svg
  src/stories/button.css
  src/stories/header.css
  src/stories/page.css
  src/style/globals.css
  src/utils/cn.ts
  tailwind.config.ts
  tsconfig.json
Labels: ⚙️ Chore

#6 [#5] Feat: RootLayout 구현
  public/next.svg
  public/vercel.svg
  public/노닥노닥.png
  src/app/_components/Introduction.tsx
  src/app/favicon.ico
  src/app/layout.tsx
  src/app/page.tsx
  src/style/globals.css
  tailwind.config.js
  tailwind.config.ts
  tsconfig.json
Labels: ✨Feature

#14 [#13] Init: msw 설정
  next.config.mjs
  package.json
  pnpm-lock.yaml
  public/mockServiceWorker.js
  src/app/layout.tsx
  src/instrumentation.ts
  src/mocks/MSWComponent.tsx
  src/mocks/browser.ts
  src/mocks/handlers/index.ts
  src/mocks/handlers/post.ts
  src/mocks/node.ts
Labels: ✨Feature, ⚙️ Chore

#19 [#18] Chore: storybook 에 msw 적용
  .storybook/main.ts
  .storybook/preview.tsx
  package.json
  pnpm-lock.yaml
  postcss.config.js
  src/mocks/handlers/post.ts
  src/stories/decorator.tsx
  src/stories/msw-exmple/msw.mdx
  src/stories/msw-exmple/msw.stories.tsx
  src/stories/msw-exmple/msw.tsx
Labels: ⚙️ Chore

#20 [#12] Feat: 메인 페이지의 게시글아이템 컴포넌트 UI구현
  .storybook/preview.tsx
  next.config.mjs
  pnpm-lock.yaml
  postcss.config.js
  src/app/_components/Introduction/index.tsx
  src/app/globals.css
  src/app/layout.tsx
  src/app/main/_component/PostItem.tsx
  src/app/main/page.tsx
  src/stories/Button.stories.ts
  src/stories/Button.tsx
  src/stories/Configure.mdx
  src/stories/Header.stories.ts
  src/stories/Header.tsx
  src/stories/Page.stories.ts
  src/stories/Page.tsx
  src/stories/assets/accessibility.png
  src/stories/assets/accessibility.svg
  src/stories/assets/addon-library.png
  src/stories/assets/assets.png
  src/stories/assets/avif-test-image.avif
  src/stories/assets/context.png
  src/stories/assets/discord.svg
  src/stories/assets/docs.png
  src/stories/assets/figma-plugin.png
  src/stories/assets/github.svg
  src/stories/assets/share.png
  src/stories/assets/styling.png
  src/stories/assets/testing.png
  src/stories/assets/theming.png
  src/stories/assets/tutorials.svg
  src/stories/assets/youtube.svg
  src/stories/button.css
  src/stories/components/Icon.stories.tsx
  src/stories/components/PostItem.stories.tsx
  src/stories/decorator.tsx
  src/stories/header.css
  src/stories/page.css
  tailwind.config.js
Labels: ✨Feature
