Repository nodak-v2/Nodak-FE, pull requests merged in 2024-07, with the labels that each got.

#152 [#151] Chore: pwa 데이터 수정
  .github/workflows/next-build.yaml
  .github/workflows/storybook.yaml
  public/app-Icon/icon-128x128.png
  public/app-Icon/icon-144x144.png
  public/app-Icon/icon-152x152.png
  public/app-Icon/icon-180x180.png
  public/app-Icon/icon-192x192.png
  public/app-Icon/icon-512x512.png
  public/app-Icon/icon.ico
  public/manifest.json
  src/app/layout.tsx
Labels: ⚙️ Chore

#149 [#148] Feat: 날짜 커스텀 유틸 함수 구현 및 적용
  src/app/(post)/result/[postId]/_components/Comments/CommentItem.tsx
  src/app/(post)/result/[postId]/_components/Posting/index.tsx
  src/app/_components/PostItem.tsx
  src/utils/formatDate.ts
Labels: ✨Feature

#143 [#142] Feat: 포스트 검색 페이지 구현
  public/icon-sprite.svg
  public/picky/Logo.png
  public/picky/kakao.png
  public/picky/kakao.svg
  public/picky/logo.svg
  src/app/(auth)/signin/page.tsx
  src/app/(post)/comment/_components/PostComment.tsx
  src/app/(post)/search/_components/SearchBar.tsx
  src/app/(post)/search/page.tsx
  src/app/_components/ChipContainer.tsx
  src/app/page.tsx
  src/app/users/profile/_components/MyVote.tsx
  src/components/Icon/type.ts
  src/components/TextInput/index.tsx
  src/components/Topbar/index.tsx
Labels: ✨Feature

#124 [#119] Feat: 인피니티 스크롤 훅 구현
  src/apis/postList.ts
  src/app/(main)/constants.ts
  src/app/(main)/utils.ts
  src/app/(post)/createPost/_components/PostForm/index.tsx
  src/app/(post)/search/page.tsx
  src/app/_components/ChipContainer.tsx
  src/app/page.tsx
  src/hooks/useInfiniteScroll.ts
Labels: ✨Feature

#169 [#168] Feat: logout 시 모든 캐시 초기화
  src/apis/logout.ts
Labels: ✨Feature

#166 [#165] Feat: pull to refresh 적용
  package.json
  pnpm-lock.yaml
  src/app/(post)/result/[postId]/page.tsx
  src/app/(post)/search/page.tsx
  src/app/page.tsx
  src/app/users/[userId]/_components/PostingList.tsx
  src/app/users/profile/(posting)/_components/PostingList/index.tsx
Labels: ✨Feature, ⚙️ Chore

#156 [#153] Feat: 팔로우 리스트 페이지
  src/apis/follow.ts
  src/app/social/[userId]/followees/page.tsx
  src/app/social/[userId]/followers/page.tsx
  src/app/social/_components/FollowButtons/FollowButton.tsx
  src/app/social/_components/FollowButtons/UnFollowButton.tsx
  src/app/social/_components/FollowList.tsx
  src/app/social/_components/ProfileBlock.tsx
  src/app/social/followees/page.tsx
  src/app/social/followers/page.tsx
  src/app/social/layout.tsx
  src/app/users/_components/ProfileBlock.tsx
  src/components/Button/Button.tsx
  src/hooks/useModal.ts
Labels: ✨Feature

#161 [#160] Feat: 프로필페이지 뱃지
  public/badge/comment-fill.svg
  public/badge/comment-line.svg
  public/badge/follow-fill.svg
  public/badge/follow-line.svg
  public/badge/like-fill.svg
  public/badge/like-line.svg
  public/badge/vote-fill.svg
  public/badge/vote-line.svg
  public/badge/write-fill.svg
  public/badge/write-line.svg
  public/icon-sprite.svg
  public/picky/user-square.svg
  src/apis/profile.ts
  src/app/users/[userId]/page.tsx
  src/app/users/_components/badge.tsx
  src/app/users/profile/edit/ImageUploader.tsx
  src/app/users/profile/page.tsx
Labels: ✨Feature

#163 [#162] Feat: dynamic meta 및 og 적용
  public/picky/thumbnail.png
  src/apis/vote.ts
  src/app/(post)/result/[postId]/_components/CommentInput/index.tsx
  src/app/(post)/result/[postId]/layout.tsx
  src/app/layout.tsx
  src/constants/meta.ts
  src/utils/getGenerateMetadata.ts
  src/utils/getMetadata.ts
Labels: ✨Feature

#177 [#176] Fix: 스크롤바가 하나 더 생기는 문제 수정
  src/app/(post)/result/[postId]/page.tsx
  src/app/(post)/search/page.tsx
  src/app/notification/page.tsx
  src/app/page.tsx
  src/app/users/[userId]/_components/PostingList.tsx
  src/app/users/profile/(posting)/_components/PostingList/index.tsx
Labels: 🛠️ Fix

#179 [#178] Feat: 댓글 기본 상태 메세지 추가 및 댓글 신고하기 옵션 추가
  src/app/(post)/result/[postId]/_components/CommentList/CommentItem/CommentItemMenu/CommentReplyItemMenu.tsx
  src/app/(post)/result/[postId]/_components/CommentList/CommentItem/CommentItemMenu/CommentRootItemMenu.tsx
  src/app/(post)/result/[postId]/_components/CommentList/index.tsx
Labels: ✨Feature

#175 [#173] Feat: 유저, 게시글 페이지의 navMore 기능 추가
  src/apis/postDetail.ts
  src/app/(post)/result/[postId]/_components/CommentList/CommentItem/CommentItemMenu/CommentReplyItemMenu.tsx
  src/app/(post)/result/[postId]/_components/CommentList/CommentItem/CommentItemMenu/CommentRootItemMenu.tsx
  src/app/(post)/result/[postId]/_components/PostDetailNavMore/index.tsx
  src/app/(post)/result/[postId]/layout.tsx
  src/app/report/layout.tsx
  src/app/report/page.tsx
  src/app/users/[userId]/layout.tsx
  src/components/Modal/ConfirmationModal.tsx
  src/components/MoreMenu/index.tsx
  src/components/Topbar/index.tsx
Labels: ✨Feature

#181 [#174] Feat: 유저 프로필에 프로필 페이지 연결
  src/apis/postDetail.ts
  src/app/(post)/createPost/_components/PostForm/index.tsx
  src/app/(post)/result/[postId]/_components/CommentList/CommentItem/CommentReplyItem.tsx
  src/app/(post)/result/[postId]/_components/CommentList/CommentItem/CommentRootItem.tsx
  src/app/(post)/result/[postId]/_components/CommentList/CommentItem/index.tsx
  src/app/(post)/result/[postId]/_components/Posting/index.tsx
  src/app/notification/_components/NotificationItem.tsx
  src/app/notification/page.tsx
  src/components/Toast/index.tsx
Labels: ✨Feature

#167 [#164] Feat: ErrorBoundary 설정 및 적용
  package-lock.json
  src/app/(post)/createPost/error.tsx
  src/app/(post)/result/[postId]/error.tsx
  src/app/error.tsx
  src/app/global-error.tsx
  src/app/not-found.tsx
  src/app/notification/error.tsx
  src/app/users/error.tsx
  src/components/EmptyPage/index.tsx
  src/components/ErrorPage/index.tsx
Labels: ✨Feature

#188 [#187] Refactor: pullToRefresh 를 페이지 레이어로 이동
  src/app/users/[userId]/_components/PostingList.tsx
  src/app/users/[userId]/page.tsx
Labels: 🔨 Refactor, 🎨 Style

#191 [#190] Fix: 댓글 관련 ui 오류 수정
  src/app/(post)/result/[postId]/_components/CommentInput/index.tsx
  src/app/(post)/result/[postId]/_components/CommentList/index.tsx
  src/app/(post)/result/[postId]/_components/CommentModalForm/CommentForm.tsx
  src/app/(post)/result/[postId]/_components/CommentModalForm/index.tsx
  src/app/(post)/result/[postId]/layout.tsx
  src/app/(post)/result/[postId]/page.tsx
  src/app/users/_components/badge.tsx
Labels: 🛠️ Fix

#193 [#192] Fix: 네비게이팅 관련 수정 사항 적용
  src/app/(post)/createPost/page.tsx
  src/app/(post)/result/[postId]/layout.tsx
  src/app/(post)/search/page.tsx
  src/app/report/layout.tsx
  src/app/social/layout.tsx
  src/app/users/[userId]/layout.tsx
  src/app/users/profile/(posting)/_components/PostingList/index.tsx
  src/app/users/profile/(posting)/layout.tsx
  src/app/users/profile/(posting)/myComment/page.tsx
  src/app/users/profile/(posting)/myLike/page.tsx
  src/app/users/profile/(posting)/myPosting/page.tsx
  src/app/users/profile/(posting)/myVoteHistory/page.tsx
  src/app/users/profile/edit/page.tsx
  src/components/Button/BackButton.tsx
  src/components/Topbar/index.tsx
  src/stories/components/Topbar.stories.tsx
Labels: 🛠️ Fix

#185 [#184] Feat: 라우팅 인증 처리 구현
  package.json
  pnpm-lock.yaml
  src/app/AuthenticatedRoute.tsx
  src/app/layout.tsx
  src/app/loading.tsx
Labels: ✨Feature, ⚙️ Chore

#197 [#196] Fix: BackButton 프롭스 제거
  src/app/chat/layout.tsx
  src/app/notification/layout.tsx
Labels: 🛠️ Fix

#203 [#202] Fix: 카테고리 관련 수정사항을 적용합니다
  src/app/(post)/createPost/_components/PostForm/index.tsx
  src/app/(post)/search/page.tsx
  src/app/_components/ChipContainer.tsx
  src/app/page.tsx
  src/components/Selector/index.tsx
  src/components/Selector/useDropdown.tsx
Labels: 🛠️ Fix

#199 [#195] Fix: 팔로워 팔로이 관련 수정사항
  src/apis/follow.ts
  src/app/(auth)/signin/page.tsx
  src/app/social/_components/FollowButtons/FollowButton.tsx
  src/app/social/_components/FollowButtons/UnFollowButton.tsx
  src/app/users/[userId]/hooks/useFollow.ts
  src/app/users/_components/ProfileBlock.tsx
Labels: 🛠️ Fix

#209 [#208] Fix: 프로필 페이지 팔로우 팔로이 카운트 캐시 오류 수정
  src/apis/follow.ts
Labels: 🛠️ Fix

#217 [#205] Refactor:게시글 작성 페이지 수정
  src/app/(post)/createPost/_components/PostForm/index.tsx
  src/app/(post)/createPost/_components/VoteForm/index.tsx
  src/app/globals.css
  src/components/TimeInput/index.tsx
Labels: 🔨 Refactor
